/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { forwardRef, useEffect, useMemo, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useThree } from '@react-three/fiber';
import * as THREE from 'three';
import { FlakesTexture } from '../assets/js/FlakesTexture';
import btnModelUrl from '../assets/models/last button.compressed.glb?url';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const Model = forwardRef<THREE.Group, any>((props, ref) => {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { scene: gltfScene } = useGLTF(btnModelUrl) as any;
  const { scene } = useThree();
  const materialReadyRef = useRef(false);

  // Generate flakes texture for material normal map (same as star)
  const flakesTexture = useMemo(() => {
    const canvas = new FlakesTexture(512, 512);
    const texture = new THREE.CanvasTexture(canvas);
    texture.wrapS = THREE.RepeatWrapping;
    texture.wrapT = THREE.RepeatWrapping;
    texture.repeat.set(10, 6);
    return texture;
  }, []);

  // Apply mirror-like material to all meshes when environment is ready
  useEffect(() => {
    if (scene.environment && !materialReadyRef.current) {
      gltfScene.traverse((child: THREE.Object3D) => {
        if (child instanceof THREE.Mesh) {
          // Mirror-like material: perfect reflection with environment map (same as star)
          const buttonMaterial = new THREE.MeshPhysicalMaterial({
            clearcoat: 1.0,
            clearcoatRoughness: 0.0,
            metalness: 1.0,
            roughness: 0.0, // Perfect mirror - reflects environment
            color: 0xffffff,
            normalMap: flakesTexture,
            normalScale: new THREE.Vector2(0.15, 0.15),
            envMap: scene.environment,
            envMapIntensity: 0.4, // Same as star
          });

          // Explicitly set envMap after creation to ensure it's applied
          buttonMaterial.envMap = scene.environment;
          buttonMaterial.envMapIntensity = 0.4;
          buttonMaterial.needsUpdate = true;

          child.material = buttonMaterial;
        }
      });
      materialReadyRef.current = true;
    }
  }, [scene.environment, gltfScene, flakesTexture]);

  return <primitive ref={ref} object={gltfScene} {...props} dispose={null} />;
});

Model.displayName = 'Model';

useGLTF.preload(btnModelUrl);
