/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { forwardRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import { useThree } from '@react-three/fiber';
import * as THREE from 'three';
import btnModelUrl from '../assets/models/btn.glb?url';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const Model = forwardRef<THREE.Group, any>((props, ref) => {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { nodes, materials } = useGLTF(btnModelUrl) as any;
  const { scene } = useThree();

  // Apply environment map to materials
  useEffect(() => {
    if (scene.environment) {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      Object.values(materials).forEach((material: any) => {
        if (material && material instanceof THREE.MeshStandardMaterial) {
          material.envMap = scene.environment;
          material.envMapIntensity = 12.0;
          material.needsUpdate = true;
        }
      });
    }
  }, [materials, scene.environment]);

  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials['Material.001']}
        position={[0, -0.096, 0]}
        scale={[2.185, 1, 0.32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve.geometry}
        material={materials.SVGMat}
        position={[-0.047, 0.239, 0.001]}
        scale={[50.76, 96.909, 50.76]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials['Material.001']}
        position={[0, 0.035, 0]}
        scale={[2.185, 1, 0.32]}
      />
    </group>
  );
});

Model.displayName = 'Model';

useGLTF.preload(btnModelUrl);
